2024-07-14 13:43:12,139 INFO: Statixbet start... [in C:\Users\HomeComp\PycharmProjects\pythonProject\statixbet\app\__init__.py:45]
2024-07-14 13:53:00,652 INFO: Statixbet start... [in C:\Users\HomeComp\PycharmProjects\pythonProject\statixbet\app\__init__.py:45]
2024-07-14 13:54:07,262 ERROR: Exception on /resend_confirmation [GET] [in C:\Users\HomeComp\PycharmProjects\pythonProject\statixbet\venv\lib\site-packages\flask\app.py:838]
Traceback (most recent call last):
  File "C:\Users\HomeComp\PycharmProjects\pythonProject\statixbet\venv\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\HomeComp\PycharmProjects\pythonProject\statixbet\venv\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\HomeComp\PycharmProjects\pythonProject\statixbet\venv\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\HomeComp\PycharmProjects\pythonProject\statixbet\venv\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\HomeComp\PycharmProjects\pythonProject\statixbet\app\routes.py", line 97, in resend_confirmation
    form = ResendConfirmationForm()
NameError: name 'ResendConfirmationForm' is not defined
2024-07-14 13:56:31,362 INFO: Statixbet start... [in C:\Users\HomeComp\PycharmProjects\pythonProject\statixbet\app\__init__.py:45]
2024-07-14 14:09:21,040 INFO: Statixbet start... [in C:\Users\HomeComp\PycharmProjects\pythonProject\statixbet\app\__init__.py:45]
2024-07-14 14:13:54,010 INFO: Statixbet start... [in C:\Users\HomeComp\PycharmProjects\pythonProject\statixbet\app\__init__.py:45]
2024-07-14 14:21:14,772 INFO: Statixbet start... [in C:\Users\HomeComp\PycharmProjects\pythonProject\statixbet\app\__init__.py:45]
2024-07-14 16:47:34,828 INFO: Statixbet start... [in C:\Users\HomeComp\PycharmProjects\pythonProject\statixbet\app\__init__.py:45]
2024-07-14 16:48:15,429 ERROR: Exception on /reset_password_request [POST] [in C:\Users\HomeComp\PycharmProjects\pythonProject\statixbet\venv\lib\site-packages\flask\app.py:838]
Traceback (most recent call last):
  File "C:\Users\HomeComp\PycharmProjects\pythonProject\statixbet\venv\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\HomeComp\PycharmProjects\pythonProject\statixbet\venv\lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\HomeComp\PycharmProjects\pythonProject\statixbet\venv\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\HomeComp\PycharmProjects\pythonProject\statixbet\venv\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\HomeComp\PycharmProjects\pythonProject\statixbet\app\routes.py", line 121, in reset_password_request
    send_password_reset_email(user)
  File "C:\Users\HomeComp\PycharmProjects\pythonProject\statixbet\app\email.py", line 17, in send_password_reset_email
    token = user.get_reset_password_token()
  File "C:\Users\HomeComp\PycharmProjects\pythonProject\statixbet\app\models.py", line 34, in get_reset_password_token
    app.config['SECRET_KEY'], algorithm='HS256')
NameError: name 'app' is not defined
2024-07-14 16:49:42,990 INFO: Statixbet start... [in C:\Users\HomeComp\PycharmProjects\pythonProject\statixbet\app\__init__.py:45]
2024-07-14 17:40:14,479 INFO: Statixbet start... [in C:\Users\HomeComp\PycharmProjects\pythonProject\statixbet\app\__init__.py:45]
